#pragma once

#define DOMAIN_LOCATION_BITS    7

#define DOMAIN_SCALE_BITS 6
#define DOMAIN_SCALE_RANGE_BITS 2
#define DOMAIN_SCALE_RANGE (1 << (DOMAIN_SCALE_RANGE_BITS - 1))

#define DOMAIN_OFFSET_BITS 7
#define DOMAIN_OFFSET_RANGE_BITS 9
#define DOMAIN_OFFSET_RANGE (1 << (DOMAIN_OFFSET_RANGE_BITS - 1))